title: Ruby Recipies
description: Code snippets and solutions to some problems I have met deveolping sinatra applications
author: "Alejandro Bertelsen"

theme: minima

base_url: /gh-pages-minima-starter
repository: abser/gh-pages-minima-starter

# Minima social links
github_username: abertelsens

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - about.md
  - archive.md

include:
    - posts

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md